"""empty message

Revision ID: 1e23fe99f319
Revises: 9259a2720974
Create Date: 2018-12-27 20:56:51.797144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e23fe99f319'
down_revision = '9259a2720974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('document_filename', sa.String(), nullable=True))
    op.add_column('post', sa.Column('document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'document_url')
    op.drop_column('post', 'document_filename')
    # ### end Alembic commands ###
