"""empty message

Revision ID: efb95fc2485c
Revises: e0bcc6046e7e
Create Date: 2018-11-22 15:41:59.707771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb95fc2485c'
down_revision = 'e0bcc6046e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=80000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_table('whisper_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=80000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('whisper_post_id', sa.Integer(), nullable=True),
    sa.Column('whisper_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['whisper_post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whisper_comment_timestamp'), 'whisper_comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whisper_comment_timestamp'), table_name='whisper_comment')
    op.drop_table('whisper_comment')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
